### ISSUE TITLE
Define challenges structure/ordering

### ISSUE THREAD

**Issue by davcri** [YouAreUto/YouAreUto#2]
We should clearly define what happens when someone creates a new challenge.

---

Currently we have challenges ordered from 1 to 5. This is reflected also in the `VictoryScreen` in which the player can select the _"Next Challenge"_.
What should happen when a user submit a new challenge? Specifically:

1. Do we want to have a specific order for challenges?
   1. If no, should we sort them by a `challenge_name` property? 
2. Do we want to separate user challenges and official challenges?
   1. If yes, should we include user challenges in the official ones periodically?

Regarding point 2, I remember discussing with @GiovanniBo about a structure like:
```
/challenges/users/<username>/<challenge-name>
```

**Comment by mp950** [comment]
1. Yes, challenges are always numerated and in order
2. No, only official challenges
